name: autoformer
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.6.9
  - pip
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - wandb
  - pip:
    - torch==1.10.1
    - tensorflow==2.3.0
    - tensorflow_addons==0.14.0
